# frozen_string_literal: true

source "https://rubygems.org"

# Add gems here if you need to use them.
# Make sure to run `bundle install` before running tests or submitting your code.

# Helps with declaratively parsing binary data.
