compile: compile_starters compile_first_stage_solutions

compile_starters:
	rm -rf ../compiled_starters/*
	bundle exec ruby scripts/compile_starters.rb

compile_first_stage_solutions:
	bundle exec ruby scripts/compile_first_stage_solutions.rb

compile_solution_diffs:
	bundle exec ruby scripts/compile_solution_diffs.rb
