compile: compile_starters

compile_starters:
	rm -rf ../compiled_starters/*
	bundle exec ruby starter_template_compiler/compile.rb

compile_first_stage_solutions:
	bundle exec ruby template_compiler/compile.rb
