compile: compile_starters

compile_starters:
	rm -rf ../compiled_starters/*
	bundle exec ruby scripts/compile_starters.rb

compile_first_stage_solutions:
	bundle exec ruby scripts/compile_first_stage_solutions.rb
