LANGUAGES = [
  Language.new(slug: "c", name: "C", repo_suffix: "c"),
  Language.new(slug: "clojure", name: "Clojure", repo_suffix: "clojure"),
  Language.new(slug: "crystal", name: "Crystal", repo_suffix: "crystal"),
  Language.new(slug: "csharp", name: "C#", repo_suffix: "csharp"),
  Language.new(slug: "elixir", name: "Elixir", repo_suffix: "elixir"),
  Language.new(slug: "go", name: "Go", repo_suffix: "go"),
  Language.new(slug: "haskell", name: "Haskell", repo_suffix: "haskell"),
  Language.new(slug: "java", name:"Java", repo_suffix: "java"),
  Language.new(slug: "javascript", name: "JavaScript", repo_suffix: "javascript"),
  Language.new(slug: "kotlin", name: "Kotlin", repo_suffix: "kotlin"),
  Language.new(slug: "nim", name: "Nim", repo_suffix: "nim"),
  Language.new(slug: "php", name: "PHP", repo_suffix: "php"),
  Language.new(slug: "python", name: "Python", repo_suffix: "python"),
  Language.new(slug: "ruby", name: "Ruby", repo_suffix: "ruby"),
  Language.new(slug: "rust", name: "Rust", repo_suffix: "rust"),
]
