hints:
  - title_markdown: "How do I access the client's TCP connection?"
    body_markdown: |-
      Use the [`accept()`](https://docs.python.org/3/library/socket.html#socket.socket.accept) method to get the client connection:

      ```python
      # The return value includes:
      # 1. the client's connection (a `Socket` object)
      # 2. the client's address (a tuple of the IP address and port number)
      connection, _ = server_socket.accept()
      ```

      The code above uses `_` to ignore the second return value, which is the client's address.

  - title_markdown: 'How do I send a response to the client?'
    body_markdown: |-
      Use the [`sendall()`](https://docs.python.org/3/library/socket.html#socket.socket.sendall) method on the client's connection:

      ```python
      # Send the response to the client
      connection.sendall(b"+PONG\r\n")
      ```

      - The `b` prefix converts the string to a [bytes object](https://docs.python.org/3/library/stdtypes.html#bytes). 
      - `+PONG\r\n` is the string "PONG" encoded as a [RESP simple string](https://redis.io/docs/latest/develop/reference/protocol-spec/#simple-strings).
