hints:
  - title_markdown: "How do I access the client's TCP connection?"
    body_markdown: |-
      Use the [`accept()`](https://ziglang.org/documentation/0.16.0/std/#std.Io.net.Server.accept) method on the server to get the client connection:

      ```zig
      const connection = try server.accept(io);
      ```

  - title_markdown: "How do I send a response to the client?"
    body_markdown: |-
      Use the [`writeAll()`](https://ziglang.org/documentation/0.16.0/std/#std.Io.Writer.writeAll) method on the client connection's writer interface:

      ```zig
      var connection_writer = connection.writer(io, &.{});
      try connection_writer.interface.writeAll("+PONG\r\n");
      ```

      `+PONG\r\n` is the string "PONG" encoded as a [RESP simple string](https://redis.io/docs/latest/develop/reference/protocol-spec/#simple-strings).
