hints:
  - title_markdown: "How do I read data from a client connection?"
    body_markdown: |-
      Use the [`getInputStream()`](https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#getInputStream--) method on the client socket and read into a byte array:

      ```clojure
      (let [in (.getInputStream sock)
            buf (byte-array 1024)]
        (.read in buf))
      ```

      - The `1024` argument specifies the size of the buffer to read into.
      - `.read` returns `-1` when the client has closed the connection, or the number of bytes read otherwise.

  - title_markdown: "How do I handle multiple commands?"
    body_markdown: |-
      Use a `loop`/`recur` to continuously read from the input stream and respond. Break out of the loop when the client disconnects (i.e., when `.read` returns `-1` or `0`):

      ```clojure
      (let [in (.getInputStream sock)
            buf (byte-array 1024)]
        (loop []
          (let [n (.read in buf)]
            (when (pos? n)
              (send-message sock "+PONG\r\n")
              (recur)))))
      ```

      This loop will keep reading commands and responding with `+PONG\r\n` until the client closes the connection.
